---
- name: Docker Playbook
  hosts: ec2
  become: true
  tasks:
    - name: Install Docker dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Login to Docker Registery
        command : docker login -u skynetskander -p nataku.hub.99

    - name: Pull Docker Image
       command: docker pull skynetskander/doc:v1

    - name: Docker Run Image
       command: docker run -d -p 80:3000 skynetskander/doc:v1 
             

    # - name: Pull Docker image
    #   docker_image:
    #     name: nginx:latest

    # - name: Create Docker container
    #   docker_container:
    #     name: my_nginx_container
    #     image: nginx:latest
    #     state: started
    #     ports:
    #       - "80:80"
    #     volumes:
    #       - "/path/to/host/dir:/path/to/container/dir"
