apiVersion: apps/v1
kind: Deployment
metadata:
  name: doc-deployment
  labels:
    app: doc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: doc
  template:
    metadata:
      labels:
        app: doc
    spec:
      containers:
      - name: doc
        image: skynetskander/doc:v2
        ports:
        - containerPort: 80

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: doc
  ports:
    - protocol: TCP
      port: 9302
      targetPort: 80